name: CI
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install
        npm run build --if-present
    - name: GitHub Action for DigitalOcean - doctl
      uses: digitalocean/action-doctl@v2.0.0
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
  